### ISSUE TITLE
Issue with searching customers in admin

### ISSUE THREAD

**Issue by xcom-magento** [NVision-Commerce-Solutions/module-customer#9]
Hello,

Our customer noticed an issue in the admin while searching customers.
For some customers there is the following error:

```
main.CRITICAL: TypeError: Commerce365\Customer\Model\Command\GetCustomerEmailById::execute(): Return value must be of type string, bool returned in /vendor/commerce365/module-customer/Model/Command/GetCustomerEmailById.php:24
```

We have fixed this by adding `bool` as accepted return type when no result is found. We think this is okay because in the parent method call (`vendor/commerce365/module-customer/Ui/Component/Listing/Column/ParentCustomer.php::42`) there is also a check when there is no email found.

Could you check this and update the module?
Thanks in advance!

**Comment by TysvdHeuvel** [comment]
Resolved in v1.0.9

**Comment by jeffreyvdwijdeven** [comment]
@TysvdHeuvel Apparently this issue still occurs. I encountered it when opening the customer list in my Magento test environment.
